---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: default

commonLabels:
  app: demo-secret

resources:
  - Pod.yaml
  - Service.yaml

replacements:
  - path: replacements/Pod.yaml
  - path: replacements/Service.yaml

